name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist

  build-amd64:
    name: Build AMD64 binary
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/dist
      - run: rustup install 1.82
      - run: rustup default 1.82
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: thermagate-amd64
          path: target/release/thermagate

  build-armv7:
    name: Build ARMv7 binary
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/dist
      - run: rustup install 1.82
      - run: rustup default 1.82
      - run: cargo install cross
      - run: cross build --release --target armv7-unknown-linux-musleabihf
      - uses: actions/upload-artifact@v4
        with:
          name: thermagate-armv7
          path: target/armv7-unknown-linux-musleabihf/release/thermagate

  release:
    name: "Create release"
    needs:
      - build-amd64
      - build-armv7
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: thermagate-amd64
          path: thermagate-amd64
      - uses: actions/download-artifact@v4
        with:
          name: thermagate-armv7
          path: thermagate-armv7
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name:
            latest
          files: |
            thermagate-amd64
            thermagate-armv7
