name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
    - run: rustup install 1.85
    - run: rustup default 1.85
    - uses: actions/checkout@v4
    - run: mkdir frontend/dist
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --all-features
